import { Providers } from "@/components/providers";
import type { Metadata } from "next";
import "./globals.css";
import prisma from "@/lib/prisma";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const game = await prisma.games.findFirst({
		where: {
			targetDate: new Date().toISOString().split("T")[0],
		},
	});

	return (
		<html lang="pt-BR">
			<body>
				<Providers targetWord={game?.word || "casas"}>{children}</Providers>
			</body>
		</html>
	);
}
